# название
name: Start

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]

# выполняемые действия
jobs:
  run_program:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          repository: ReyLegar/second_ent
          ref: main

      - name: Run program
        run: python print_text.py
